import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function POST(request: Request) {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await request.json() as {
    name: string;
    competition_id: string;
    is_public: boolean;
    auto_pick_enabled: boolean;
  };

  if (!body.name?.trim() || !body.competition_id) {
    return NextResponse.json({ error: "Name and competition_id are required" }, { status: 400 });
  }

  // Generate slug
  const base = body.name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
  const suffix = Math.random().toString(36).slice(2, 6);
  const slug = `${base}-${suffix}`;

  // Insert league (invite_code generated by DB default)
  const { data: league, error: leagueError } = await supabase
    .from("leagues")
    .insert({
      name: body.name.trim(),
      competition_id: body.competition_id,
      is_public: body.is_public,
      auto_pick_enabled: body.auto_pick_enabled,
      slug,
      created_by: user.id,
    })
    .select("id, slug, invite_code")
    .single();

  if (leagueError || !league) {
    return NextResponse.json({ error: leagueError?.message ?? "Failed to create league" }, { status: 500 });
  }

  // Insert owner membership
  const { error: memberError } = await supabase.from("league_memberships").insert({
    league_id: league.id,
    user_id: user.id,
    role: "owner",
    is_eliminated: false,
  });

  if (memberError) {
    return NextResponse.json({ error: memberError.message }, { status: 500 });
  }

  return NextResponse.json({ slug: league.slug, invite_code: league.invite_code });
}
