"use client";

import type { LeagueData, ParseError } from "@/lib/spreadsheet/types";
import LeagueSummary from "./report/LeagueSummary";
import SurvivalLeaderboard from "./report/SurvivalLeaderboard";
import PickHistoryGrid from "./report/PickHistoryGrid";
import EliminationTimeline from "./report/EliminationTimeline";
import TeamUsage from "./report/TeamUsage";

type Props = {
  data: LeagueData;
  warnings: ParseError[];
  onReset: () => void;
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="glass-card p-6 md:p-8 flex flex-col gap-6 print:shadow-none print:border print:border-gray-200 print:rounded-none">
      <h2
        className="font-display font-bold text-lg uppercase tracking-widest"
        style={{ color: "var(--lmx-text)" }}
      >
        {title}
      </h2>
      {children}
    </div>
  );
}

export default function ReportView({ data, warnings, onReset }: Props) {
  const handlePrint = () => window.print();

  return (
    <div id="lmx-report">
      {/* Report header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8 print:hidden">
        <div>
          <h1 className="font-display font-bold text-2xl" style={{ color: "var(--lmx-text)" }}>
            {data.leagueName ?? "League Report"}
          </h1>
          <p className="text-sm mt-1" style={{ color: "var(--lmx-text-muted)" }}>
            {data.players.length} player{data.players.length !== 1 ? "s" : ""} ·{" "}
            {data.picks.length} pick{data.picks.length !== 1 ? "s" : ""}
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={handlePrint}
            className="px-5 py-2.5 rounded-lg font-display font-bold text-sm transition-all hover:opacity-90"
            style={{ background: "var(--lmx-green)", color: "var(--lmx-surface)" }}
          >
            Print / Save PDF
          </button>
          <button
            onClick={onReset}
            className="px-5 py-2.5 rounded-lg font-display font-bold text-sm border transition-all hover:opacity-80"
            style={{ borderColor: "var(--lmx-surface-edge)", color: "var(--lmx-text-muted)" }}
          >
            Upload different file
          </button>
        </div>
      </div>

      {/* Print header (only visible when printing) */}
      <div className="hidden print:block mb-6">
        <h1 className="text-2xl font-bold">{data.leagueName ?? "League Report"}</h1>
        <p className="text-sm text-gray-500">
          Generated by LMX · {new Date().toLocaleDateString()}
        </p>
      </div>

      {/* Warnings */}
      {warnings.length > 0 && (
        <div
          className="mb-6 p-4 rounded-lg border print:hidden"
          style={{ borderColor: "var(--lmx-amber)", background: "rgba(245,158,11,0.06)" }}
        >
          <p
            className="font-display font-bold text-sm uppercase tracking-widest mb-2"
            style={{ color: "var(--lmx-amber)" }}
          >
            {warnings.length} warning{warnings.length !== 1 ? "s" : ""}
          </p>
          <ul className="flex flex-col gap-1">
            {warnings.map((w, i) => (
              <li key={i} className="text-sm" style={{ color: "var(--lmx-text-muted)" }}>
                · {w.message}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Report sections */}
      <div className="flex flex-col gap-6">
        <Section title="League Summary">
          <LeagueSummary data={data} />
        </Section>

        <Section title="Survival Leaderboard">
          <SurvivalLeaderboard data={data} />
        </Section>

        <Section title="Pick History">
          <PickHistoryGrid data={data} />
        </Section>

        <Section title="Elimination Timeline">
          <EliminationTimeline data={data} />
        </Section>

        <Section title="Team Usage">
          <TeamUsage data={data} />
        </Section>
      </div>
    </div>
  );
}
